; PlatformIO Project Configuration File

[platformio]
default_envs = nanoatmega328new

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200

build_src_filter =
    +<*>
    -<hal_gpio_avr.c>


[env:native_button]
platform = native
test_framework = unity

test_filter = test_button
test_build_src = yes

build_src_filter =
    -<*>
    +<button.cpp>

build_flags =
    -Isrc

[env:native_hx711]
platform = native
test_framework = unity

test_filter = test_hx711_driver
test_build_src = yes

build_src_filter =
    -<*>
    +<hx711_driver.c>

build_flags =
    -Isrc

[env:native_level_indicator]
platform = native
test_framework = unity

test_filter = test_level_indicator
test_build_src = yes

build_src_filter =
    -<*>
    +<level_indicator.cpp>

build_flags =
    -Isrc

[env:native_operation_indicator]
platform = native
test_framework = unity

test_filter = test_operation_indicator
test_build_src = yes

build_src_filter =
    -<*>
    +<operation_indicator.cpp>

build_flags =
    -Isrc