; PlatformIO Project Configuration File

[platformio]
default_envs = nanoatmega328new

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200

build_src_filter =
    +<*>
    -<hal_gpio_arduino.cpp>
    -<hal_time_arduino.cpp>
    -<hal_storage_arduino.cpp>
    -<hal_serial_arduino.cpp>
    -<main_avr.cpp>


[env:nanoatmega328new_baremetal]
platform = atmelavr
board = nanoatmega328new
monitor_speed = 115200

build_src_filter =
    +<*>
    -<main_arduino.cpp>
    -<hal_gpio_arduino.cpp>
    -<hal_time_arduino.cpp>
    -<hal_storage_arduino.cpp>
    -<hal_serial_arduino.cpp>


[env:native_button]
platform = native
test_framework = unity

test_filter = test_button
test_build_src = yes

build_src_filter =
    -<*>
    +<button.cpp>

build_flags =
    -Isrc

[env:native_hx711]
platform = native
test_framework = unity

test_filter = test_hx711_driver
test_build_src = yes

build_src_filter =
    -<*>
    +<hx711_driver.c>

build_flags =
    -Isrc

[env:native_level_indicator]
platform = native
test_framework = unity

test_filter = test_level_indicator
test_build_src = yes

build_src_filter =
    -<*>
    +<level_indicator.cpp>

build_flags =
    -Isrc

[env:native_operation_indicator]
platform = native
test_framework = unity

test_filter = test_operation_indicator
test_build_src = yes

build_src_filter =
    -<*>
    +<operation_indicator.cpp>

build_flags =
    -Isrc

[env:native_scale]
platform = native
test_framework = unity

test_filter = test_scale
test_build_src = yes

build_src_filter =
    -<*>
    +<scale.cpp>

build_flags =
    -Isrc

[env:native_calibration_storage]
platform = native
test_framework = unity

test_filter = test_calibration_storage
test_build_src = yes

build_src_filter =
    -<*>
    +<calibration_record.cpp>
    +<calibration_storage.cpp>

build_flags =
    -Isrc

[env:native_console]
platform = native
test_framework = unity

test_filter = test_console
test_build_src = yes

build_src_filter =
    -<*>
    +<console.c>

build_flags =
    -Isrc

[env:native_time_delay]
platform = native
test_framework = unity

test_filter = test_time_delay
test_build_src = yes

build_src_filter =
    -<*>
    +<hal_time_delay.c>

build_flags =
    -Isrc